spring.datasource.url=jdbc:postgresql://localhost:5432/pulsepass
spring.datasource.username=pulsepass
spring.datasource.password=pulsepass

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true